version: '3'
services:
  python3:
    restart: always
    build: .
    working_dir: '/src/'
    tty: true
    command: "jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
    env_file: .env
    ports:
      - 8888:8888
    volumes:
      - ./:/src
